global:
  storageClass: standard-rwo

clickhouse:
  installCustomStorageClass: true
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1500m
      memory: 4Gi

postgresql:
  enabled: true
signoz:
  image: 
    registry: us-east1-docker.pkg.dev
    repository: kip-dev-487617-t9/kip-dev/kip
    tag: main-3c96838
  env:
    signoz_web_enabled: "false"

otelCollector:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 16
            auth:
              authenticator: bearertokenauth
          http:
            endpoint: 0.0.0.0:4318
    extensions:
      bearertokenauth:
        scheme: "Bearer"
        token: "randomtoken"
    service:
      extensions: [health_check, zpages, pprof, bearertokenauth]